### ISSUE TITLE
Is this script working properly

### ISSUE THREAD

**Issue by Mbnl1197** [qba73/nc#1]
Hi,
 I see that the page displays "all checks have failed". I want to know that this script can be used normally.

Thanks!

**Comment by qba73** [comment]
@Mbnl1197 which page? could you please provide link? The script was developed years ago and worked correctly with old version of Python 2.x (not supported today). I do not know if the script works ok on Python 3.x.

**Comment by Mbnl1197** [comment]
Oh ! It seems to be my problem. It just appeared on the "code" page, but it doesn't exist now.
Thank you for your quick reply!
